[theme]
primaryColor = "#4F46E5"
backgroundColor = "#05050A"
secondaryBackgroundColor = "#0A0A12"
textColor = "#F3F3F5"
font = "sans serif"
base = "dark"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
